apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amp-scanner-gen-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: 776389595347.dkr.ecr.us-west-2.amazonaws.com
    chart: sib/helmcharts/ares/amp-scanner-gen
    targetRevision: 0.1.2
    helm:
      releaseName: amp-scanner-gen-dev
      valuesObject:
        namespace: mars
        fullnameOverride: amp-scanner-gen
        image:
          repository: 776389595347.dkr.ecr.us-west-2.amazonaws.com/ares/amp-scanner-gen
          tag: local-vm-setup-gcp
          pullPolicy: IfNotPresent
        imagePullSecrets:
          - name: ecr-regcred
        replicas: 1
        certManager:
          enabled: true
          issuerName: default-ca
        externalSecrets:
          enabled: true
          secretStoreName: aws-ares
          secretStoreKind: ClusterSecretStore
          apiEncryptionKey: stage/scanners/amp-scanner/cache.encryption.key
          apiEncryptionProperty: repository.apiEncryptionKey
          awsAccessKeyIdKey: stage/scanners/amp-scanner/ampscanner-dev-dynamodb-read-write/access.key
          awsSecretAccessKeyKey: stage/scanners/amp-scanner/ampscanner-dev-dynamodb-read-write/secret.key
          sovAwsAccessKeyIdKey: stage/scanners/amp-scanner/ampscanner-sov-int-dynamodb-read-write/access.key
          sovAwsSecretAccessKeyKey: stage/scanners/amp-scanner/ampscanner-sov-int-dynamodb-read-write/secret.key
          datadogApiKey: stage/scanners/amp-scanner-gen/avalon.datadog.api.key
          datadogApiProperty: metrics.datadog.apikey
          keystorePasswordKey: stage/scanners/amp-scanner/keystore.pass
          keystorePasswordProperty: server.ssl.key-store-password
          ampkitActivationCodeKey: stage/scanners/amp-scanner/ampkit.activation.code
          ampkitActivationCodeProperty: client.ampkit.activationCode
          ampkitCarrierIdKey: stage/scanners/amp-scanner/ampkit.carrier.id
          ampkitCarrierIdProperty: client.ampkit.carrierId
        resources:
          requests:
            cpu: 500m
            memory: 2Gi
            ephemeral-storage: 250Mi
          limits:
            cpu: "2"
            memory: 4Gi
        emptyDirs:
          ampLog: 100Mi
          ampCerts: 10Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: mars
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
