apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitdefender-scanner-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: 776389595347.dkr.ecr.us-west-2.amazonaws.com
    chart: sib/helmcharts/ares/bitdefender-scanner
    targetRevision: 0.1.2
    helm:
      releaseName: bitdefender-scanner-dev
      valuesObject:
        namespace: mars
        fullnameOverride: bitdefender
        image:
          repository: 776389595347.dkr.ecr.us-west-2.amazonaws.com/ares/bitdefender
          tag: master-202605011451-d67b5efa
          pullPolicy: IfNotPresent
        imagePullSecrets:
          - name: ecr-regcred
        replicas: 1
        certManager:
          enabled: true
          issuerName: default-ca
        externalSecrets:
          enabled: true
          secretStoreName: aws-ares
          secretStoreKind: ClusterSecretStore
          keystoreSecretKey: dev/scanners/bitdefender/keystore.pass
          productIdSecretKey: dev/scanners/bitdefender/bitdefender.product.id
          awsCredentialsSecretKey: dev/scanners/bitdefender/aws-credentials
          awsCredentialsAccessKeyProperty: accessKeyId
          awsCredentialsSecretKeyProperty: secretAccessKey
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: "2"
            memory: 4Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: mars
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
