apiVersion: generators.external-secrets.io/v1alpha1
kind: ECRAuthorizationToken
metadata:
  name: bitdefender-ecr-token
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  region: us-west-2
  auth:
    secretRef:
      accessKeyIDSecretRef:
        name: aws-ares-creds
        namespace: argocd
        key: access-key
      secretAccessKeySecretRef:
        name: aws-ares-creds
        namespace: argocd
        key: secret-access-key
      sessionTokenSecretRef:
        name: aws-ares-creds
        namespace: argocd
        key: session-token
