apiVersion: generators.external-secrets.io/v1alpha1
kind: ECRAuthorizationToken
metadata:
  name: bitdefender-ecr-token
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  region: us-west-2
