apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: threatgrid-services-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: 776389595347.dkr.ecr.us-west-2.amazonaws.com
    chart: sib/helmcharts/ares/threatgrid-services
    targetRevision: 0.1.0
    helm:
      releaseName: threatgrid-services-dev
      valuesObject:
        namespace: mars
        fullnameOverride: threatgrid-services
        image:
          repository: 776389595347.dkr.ecr.us-west-2.amazonaws.com/ares/threatgrid-services
          tag: local-vm-setup-gcp
          pullPolicy: IfNotPresent
        imagePullSecrets:
          - name: ecr-regcred
        replicas: 1
        certManager:
          enabled: true
          issuerName: default-ca
        externalSecrets:
          enabled: true
          secretStoreName: aws-ares
          secretStoreKind: ClusterSecretStore
          awsAccessKeyKey: stage/scanners/threatgrid-services/threatgrid-services-dev-dynamodb-read-write/access.key
          awsSecretKeyKey: stage/scanners/threatgrid-services/threatgrid-services-dev-dynamodb-read-write/secret.key
          awsKmsAccessKeyKey: stage/scanners/threatgrid-services/kms_threatgrid_stage_apikey_encryption/access.key
          awsKmsSecretKeyKey: stage/scanners/threatgrid-services/kms_threatgrid_stage_apikey_encryption/secret.key
          oemTokenUsKey: stage/scanners/threatgrid-services/oem/test_token
          oemTokenEuKey: stage/scanners/threatgrid-services/oem/test_token
          oemTokenIndKey: stage/scanners/threatgrid-services/oem/test_token
          oemTokenAusKey: stage/scanners/threatgrid-services/oem/test_token
          keystorePasswordKey: stage/scanners/threatgrid-services/keystore.pass
          keystorePasswordProperty: server.ssl.key-store-password
          datadogApiKey: stage/scanners/threatgrid-services/datadog.api.key
          jwtPublicKeyKey: stage/scanners/threatgrid-services/jwt/public.key
          apiGatewayClientIdKey: stage/scanners/threatgrid-uploader/apigw/client_id
          apiGatewayClientSecretKey: stage/scanners/threatgrid-uploader/apigw/client_secret
          includeSovSecrets: true
          sovAwsAccessKeyKey: stage/scanners/threatgrid-services/sov-threatgrid-services-int-dynamodb-read-write/access.key
          sovAwsSecretKeyKey: stage/scanners/threatgrid-services/sov-threatgrid-services-int-dynamodb-read-write/secret.key
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
            ephemeral-storage: 250Mi
          limits:
            cpu: "2"
            memory: 4Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: mars
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
